export { default as IcCloudsSnow } from "./IcCloudsSnow";
export { default as IcClouds } from "./IcClouds";
export { default as IcLightning } from "./IcLightning";
export { default as IcMap } from "./IcMap";
export { default as IcSearch } from "./IcSearch";
export { default as IcSunCloudsRain } from "./IcSunCloudsRain";
export { default as IcSunClouds } from "./IcSunClouds";
export { default as IcSun } from "./IcSun";
export { default as IcWeather } from "./IcWeather";
